Export ndb/glib_version
logicalclocks/ndb-chef pull request #191
Opened 2024-04-09 17:50 UTC by svenssonaxel

2024-04-09 17:53 UTC, kouzant requested changes

2024-04-09 17:53 UTC, kouzant commented on metadata.rb
> +          :desctiption => "glibc version",
```suggestion
          :description => "glibc version",
```

2024-04-16 08:44 UTC, svenssonaxel commented
@kouzant Good catch, ready to squash and merge. I hope, because I have no chef experience.

2024-04-16 08:46 UTC, kouzant approved these changes

2024-04-16 09:06 UTC, merged